site_name: Arrowhead Guide
theme:
  name: material
  language: sl
  palette:
    primary: indigo
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/field.ico

nav:
  - En:
      - Instead of an introduction: en/getting-started.md
      - Distances: en/distances.md
      - Distance Estimation: en/estimation.md
      - Test: en/test.md
      - Oblique throw: en/graph.md
      - Sofa: en/sofa.md
  - Sl:
      - Namesto uvoda: sl/getting-started.md
      - Razdalje: sl/distances.md
      - Ocenjevanje razdalj: sl/estimation.md
      - Test: sl/test.md
      - PoÅ¡evni met: sl/graph.md
      - KavÄ: sl/sofa.md
      - Skrivnostni obrat: sl/mystery.md
      - Pred tekmovanjem: sl/other.md

  #- Sr:
  #    - Arrowhead Guide: sr/index.md 

plugins:
  - search
  # - inline-svg-mod
  # - include-markdown

extra_css:
  - stylesheets/extra.css
  
extra_javascript:
  - js/language_switcher.js

extra:
  search:
    language: en
  alternate:
    - name: ğŸ‡¬ğŸ‡§ English
      link: /en/
    - name: ğŸ‡¸ğŸ‡® SlovenÅ¡Äina
      link: /sl
    - name: ğŸ‡·ğŸ‡¸ Srpski
      link: /sr
