site_name: Arrowhead Guide
theme:
  name: material
  custom_dir: overrides
  language: sl
  palette:
    primary: indigo
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/field.ico

nav:
  - En:
      - Instead of an introduction: en/getting-started.md
      - Distances: en/distances.md
      - Distance Estimation: en/estimation.md
      - Test: en/test.md
      - Oblique throw: en/graph.md
      - Sofa: en/sofa.md
      - Before the competition: en/other.md
      - Calculator: en/calculate.md
      - Finally: en/about.md
      - Opinions: en/feedback.md
  - Sl:
      - Namesto uvoda: sl/getting-started.md
      - Postavitev: sl/position.md
      - Levo - desno: sl/left-right.md
      - Razdalje: sl/distances.md
      - Ocenjevanje razdalj: sl/estimation.md
      - Test: sl/test.md
      - Po≈°evni met: sl/graph.md
      - Kavƒç: sl/sofa.md
      # - Skrivnostni obrat: sl/mystery.md
      - Pred tekmovanjem: sl/other.md
      - Kalkulator: sl/calculate.md
      - Za konec: sl/about.md
      - Mnenja: sl/feedback.md

  - Sr:
      - –£–º–µ—Å—Ç–æ —É–≤–æ–¥–∞: sr/getting-started.md
      - –£–¥–∞—ô–µ–Ω–æ—Å—Ç–∏: sr/distances.md
      - –ü—Ä–æ—Ü–µ–Ω–∞ —É–¥–∞—ô–µ–Ω–æ—Å—Ç–∏: sr/estimation.md
      - –¢–µ—Å—Ç: sr/test.md
      - –ö–æ—Å–æ –±–∞—Ü–∞—ö–µ: sr/graph.md
      - –°–æ—Ñ–∞: sr/sofa.md
      - –ü—Ä–µ —Ç–∞–∫–º–∏—á–µ—ö–∞: sr/other.md
      # - –ú–∏—Å—Ç–µ—Ä–∏–æ–∑–Ω–∏ –∑–∞–æ–∫—Ä–µ—Ç: sr/mystery.md
      - –ö–∞–ª–∫—É–ª–∞—Ç–æ—Ä: sr/calculate.md
      - –ö–æ–Ω–∞—á–Ω–æ: sr/about.md
      - –ú–∏—à—ô–µ—ö–∞: sr/feedback.md

# plugins:
#  - search
plugins:
  - search:
      enabled: false


extra_css:
  - stylesheets/extra.css
  - stylesheets/arrowhead.css

markdown_extensions:
  - md_in_html

extra_javascript:
  - js/global.js
  - js/language_switcher.js
  - js/login.js
  # - js/logout.js

extra:
#  search:
#    language: en
  alternate:
    - name: üá¨üáß English
      link: en/getting-started
    - name: üá∏üáÆ Sloven≈°ƒçina
      link: sl/getting-started
    - name: üá∑üá∏ Srpski
      link: sr/getting-started
