site_name: Arrowhead navodila za uporabo
theme:
  name: material
  custom_dir: overrides
  language: sl
  palette:
    primary: indigo
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/field.ico

nav:
  #- En:
  #    - Instead of an introduction: en/getting-started.md
  #    - Position: en/position.md
  #    - Left - right: en/left-right.md
  #    - Distances: en/distances.md
  #    - Distance Estimation: en/estimation.md
  #    - Test: en/test.md
  #    - Oblique throw: en/graph.md
  #    - Sofa: en/sofa.md
  #    - Before the competition: en/other.md
  #    - Calculator: en/calculate.md
  #    - Finally: en/about.md
  #    - Opinions: en/feedback.md
  - Sl:
      - Namesto uvoda: sl/getting-started.md
      - Zgodba o po≈°evnem metu: sl/graph.md
      - Ocenjevanje razdalj:
          - Razdalje: sl/estimation/distances.md
          - Metode: sl/estimation/estimation.md
          - Test viziranja: sl/estimation/test.md
      - Fizikalne osnove:
          - Teorija: sl/theory/index.md
          - Po≈°evni met: sl/theory/theory.md
          - Skrivnostni obrat: sl/theory/mystery.md
      - Optiƒçne prevare:
          - Osnove: sl/illusions/index.md 
          - Arrowhead: sl/illusions/illusions.md
          - Levo - desno: sl/illusions/left-right.md
          - Primeri:
                - Geometrijske iluzije: sl/illusions/geometry.md
                - Iluzorne konture: sl/illusions/contures.md
                - Svetlobne iluzije: sl/illusions/colors.md
                - Nemogoƒçi predmeti: sl/illusions/impossible.md
                - Ostalo: sl/illusions/misc.md
      - Postavitev: sl/position.md
      - Kavƒç: sl/sofa.md
      - Pred tekmovanjem: sl/other.md
      - Kalkulator: sl/calculate.md
      - Print: sl/print.md
      - Za konec: sl/about.md
      - Mnenja: sl/feedback.md

  - Sr:
      - –£–º–µ—Å—Ç–æ —É–≤–æ–¥–∞: sr/getting-started.md
      - –†–∞—Å–ø–æ—Ä–µ–¥: sr/position.md     
      - –õ–µ–≤–æ - –î–µ—Å–Ω–æ: sr/left-right.md
      - –£–¥–∞—ô–µ–Ω–æ—Å—Ç–∏: sr/distances.md
      - –ü—Ä–æ—Ü–µ–Ω–∞ —É–¥–∞—ô–µ–Ω–æ—Å—Ç–∏: sr/estimation.md
      - –¢–µ—Å—Ç: sr/test.md
      - –ö–æ—Å–æ –±–∞—Ü–∞—ö–µ: sr/graph.md
      - –°–æ—Ñ–∞: sr/sofa.md
      - –ü—Ä–µ —Ç–∞–∫–º–∏—á–µ—ö–∞: sr/other.md
      - –ö–∞–ª–∫—É–ª–∞—Ç–æ—Ä: sr/calculate.md
      - –ö–æ–Ω–∞—á–Ω–æ: sr/about.md
      - –ú–∏—à—ô–µ—ö–∞: sr/feedback.md

# plugins:
#  - search
plugins:
  - search:
      enabled: false


extra_css:
  - stylesheets/extra.css
  - stylesheets/arrowhead.css
  - stylesheets/print.css

markdown_extensions:
  - md_in_html
  #- pymdownx.arithmatex:
  #    generic: false


extra_javascript:
  - js/global.js
  - js/language_switcher.js
  - js/login.js
  - js/print.js
  # - js/logout.js
  #- js/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
#  search:
#    language: en
  alternate:
    #- name: üá¨üáß English
    #  link: en/getting-started
    - name: üá∏üáÆ Sloven≈°ƒçina
      link: sl/getting-started
    - name: üá∑üá∏ Srpski
      link: sr/getting-started
